required = ["github.com/json-iterator/go"]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.12.1"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "v1.1.5"

[prune]
  go-tests = true
  unused-packages = true
